🔄 synced local '.github/workflows/' with remote '.github/workflows/'

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -56,11 +56,12 @@ jobs:
             ${{ runner.os }}-go-validate-${{ hashFiles('**/go.sum') }}-
             ${{ runner.os }}-go-validate-
 
-      - name: Install `govulncheck` and `gopls`
+      - name: Install `govulncheck`, `gopls`, `modfmt` and `ghokin`
         run: |
           go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
           go install golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@v0.20.0
           go install github.com/abhijit-hota/modfmt@v0.0.0-20260105113844-287023c3d905
+          go install github.com/PaddleHQ/ghokin/v4@d054884a017238b0dd9599698d1bb44193278446 # v4.0.3
 
       - name: Setup test databases
         uses: ./.github/actions/setup-databases
@@ -111,6 +112,12 @@ jobs:
           go generate ./...
           git diff --exit-code || \
             (echo '::error title=Incorrect Generated Files::Please run "go generate ./..."' && exit 1)
+
+      - name: Check feature file formatting
+        run: |
+          [ -d "features/" ] || exit 0
+          ghokin check features/ || \
+            (echo '::error title=Incorrect feature file formatting::Please run "go run github.com/PaddleHQ/ghokin/v4@d054884a017238b0dd9599698d1bb44193278446 fmt replace features/" to fix' && exit 1)
 
       # --
       # Go Vulncheck
